TateElectricals/TateElectricals/Controllers/BasicOperationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TateElectricals.Models;
using TateElectricals.DataModels;
using TateElectricals.DataLayer;
namespace TateElectricals.Controllers
{
    public class BasicOperationsController : Controller
    {
        private readonly ILogger<BasicOperationsController> _logger;
        private IProductRepository IProductRepository
        { get; set; }
        public BasicOperationsController(ILogger<BasicOperationsController> logger, IProductRepository productRepository)
        {
           
            IProductRepository = productRepository;
            _logger = logger;
            if (SessionManager.SessionManager.Current.AgencyViewModel == null)
            {
                SessionManager.SessionManager.Current = new SessionManager.SessionManager();
                AgencyViewModel = new AgencyViewModel();
                SessionManager.SessionManager.Current.AgencyViewModel = AgencyViewModel;
            }
            else
            {
                AgencyViewModel = SessionManager.SessionManager.Current.AgencyViewModel;
            }
        }
        public IAgencyViewModel AgencyViewModel { get; set; }

        [Route("MyHome")]
        public IActionResult HomePage()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        [Route("AddGetPass")]
        public IActionResult AddGetPass()
        {
            try
            {
                ViewBag.MSED= IProductRepository.GetMSED();
                ViewBag.deptinfo = AgencyViewModel.SelectedUser.department;
                return PartialView("GetPass");
            }
            catch (Exception ex)
            {
                return View();
            }

        }
        [Route("SaveGatePass")]
        public IActionResult SaveGatePass(GatePassDetail GPDetail, TranformerDetail TranDetail, GatePassTranfomerConfiguration gtc)
        {
            GatePassTranfomerConfiguration td = IProductRepository.SaveGatePass(GPDetail, TranDetail, ref gtc);
            return Json(new { td });
        }

        [Route("AddGetPassOil")]
        public IActionResult GetPassOil()
        {
            try
            {
                ViewBag.MSED = IProductRepository.GetMSED();
               // ViewBag.deptinfo = HomeController.dept;
                
                //return  View();
                return PartialView("GetPassOil");
            }
            catch (Exception ex)
            {
                return View();
            }

        }
        [Route("SaveGetPassOil")]
        public IActionResult SaveGetPassOil(OilPassDetail OilPasss, int TotalOilRecieved)
        {
            OilPasss.DepartmentId = 6271539;//take from login user
            bool isSaved = IProductRepository.SaveOilPass( OilPasss, TotalOilRecieved);
            return Json(new { isSaved });

        }
        [Route("GetOilDetails")]
        public IActionResult GetOilDetails(int currentPage = 1, int PageSize = 2)
        {
            int id = 0;// take i from session 
            object Dlist = IProductRepository.GetOilDetails(currentPage, PageSize);
            return Json(new { Dlist });
        }

        [Route("Home")]
        public IActionResult Home()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        [Route("GetTrans")]
        public IActionResult GetTrans(string Date = "", int JobNo = 0, int TokenNo = 0, int currentPage = 1, int PageSize = 2)
        {
            try
            {
                var Dlist = IProductRepository.GetTransformr(Date, JobNo, TokenNo, currentPage, PageSize);
                return Json(new { Dlist });
            }
            catch (Exception ex)
            {
                return View();
            }

        }
        [Route("ViewITR")]
        public IActionResult TRInfo()
        {
            try
            {
                
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        [Route("AdminView")]
        public IActionResult AdminHome()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        [Route("Users")]
        public IActionResult vwUser()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        [Route("Departments")]
        public IActionResult vwDepartment()
        {
            return View();
        }
        [Route("SaveDepartments")]
        public IActionResult SaveDepartments( SystemUser systemuser)
        {
            bool isSaved = IProductRepository.SaveSystemUser( systemuser);
            return Json(new { isSaved });
        }
        [Route("GetDepartments")]
        public IActionResult GetDepartments()
        {
            int id = 0;// take i from session 
             object Dlist = IProductRepository.GetSystemUser(id);
            return Json(new { Dlist });
        }

        #region MSED

        [Route("MSED")]
        public IActionResult vwmsed()
        {
            return View();

        }

        [Route("SaveMSED")]
        public IActionResult SaveMSED(MsebDetail MSED)
         {
            bool isSaved = IProductRepository.SaveMsebDetail(MSED);
            return Json(new { isSaved });
        }
        [Route("GetMSED")]
        public IActionResult GetMSED()
        {
            List<MsebDetail> Dlist = IProductRepository.GetMSED();
            return Json(new { Dlist });
        }
        //[Route("DeleteMSED")]
        //public IActionResult DeleteMSED(int MSEDID)
        //{
        //    MsebDetail obj = new MsebDetail() { MsebDetailID = MSEDID ,EntityState=EntityState.Deleted};
        //     bool isSaved = IProductRepository.SaveMsebDetail(obj);
        //    return Json(new { isSaved}) ;
        //}
        #endregion


        #region Print
        [Route("PrintGetPass")]
        public IActionResult PrintGetPass(int GetpassdetailID)
        {
            
            string Dlist = IProductRepository.PrintGetPass(GetpassdetailID);
            return Json(new { Dlist });
        }

        #endregion

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        








    }
}

TateElectricals/TateElectricals/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TateElectricals.Models;
using System.Web;
using TateElectricals.DataLayer;
using TateElectricals.DataModels;

namespace TateElectricals.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

      // public static List<Department> dept = new List<Department>();
        private IProductRepository IProductRepository
        { get; set; }
        public HomeController(ILogger<HomeController> logger, IProductRepository productRepository)
        {
            IProductRepository = productRepository;
            _logger = logger;
            if (SessionManager.SessionManager.Current == null)
            {
                SessionManager.SessionManager.Current = new SessionManager.SessionManager();
                AgencyViewModel = new AgencyViewModel();
                SessionManager.SessionManager.Current.AgencyViewModel = AgencyViewModel;
            }
            else
            {
                AgencyViewModel = SessionManager.SessionManager.Current.AgencyViewModel;
            }

            if (AgencyViewModel == null)
            {
                RedirectToPagePermanent("~/Home/LoginPage");
            }
        }
        public IAgencyViewModel AgencyViewModel { get; set; }
        public IActionResult LoginPage()
        {   
            return View();
        }

        [Route("Logout")]
        public IActionResult LogOut()
        {
            // dept = new List<Department>();
            AgencyViewModel.SelectedUser = null;
            return Json(new { IsLoggedIn = true });
        }

        public IActionResult LoginModel(string uName,string uPass)
        {
            //string uPass = "1234";
            var d = IProductRepository.ValidateSystemUser(uName, uPass);

            if (d != null) { 
               // dept.Add(d.department);
                AgencyViewModel.SelectedUser = d;
                
            return Json(new { IsLoggedIn = AgencyViewModel.SelectedUser.department.DepartmentType.ToString() });
            }
            else return Json(new { IsLoggedIn = "No Valid" });
           // if (uName== "admin")
           // return Json(new { IsLoggedIn = "admin" });
           //else if(uName=="pcontrol")
           //     return Json(new { IsLoggedIn = "Agency" });
          // else return Json(new { IsLoggedIn = "False" });

        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TateElectricals/TateElectricals/Views/Home/LoginPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>
    <meta charset="utf-8" />
    <title>Tate Electricals</title>
    <meta name="description" content="" />
    <meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <!-- WEB FONTS : use %7C instead of | (pipe) -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />

    <!-- CORE CSS -->
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- THEME CSS -->
    <link href="/assets/css/essentials.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/layout.css" rel="stylesheet" type="text/css" />

    <!-- PAGE LEVEL SCRIPTS -->
    <link href="/assets/css/header-1.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/color_scheme/green.css" rel="stylesheet" type="text/css" id="color_scheme" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        .custgrdt {
            background-image: linear-gradient(182deg, rgba(175, 120, 76, 0.6) 0%, rgba(84, 163, 163, 0.13) 68%);
        }
    </style>
</head>


<body class="smoothscroll enable-animation">

    
    <!-- wrapper -->
    <div id="wrapper" style="background-image: url('https://localhost:44397/assets/images/LoginBg.jpg');background-size:cover; ">
       
      
        <div id="header" class="clearfix transparent" style="border-bottom:none;">

            <!-- TOP NAV -->
            <header id="topNav">
                <div class="container">

                    <!-- Mobile Menu Button -->
                    <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- BUTTONS -->
                    <!-- /BUTTONS -->
                    <!-- Logo -->
                    <a class="logo pull-left" href="index.html">
                        <img src="assets/images/_smarty/logo_dark.png" alt="" style="max-width:118px;"/>
                    </a>

                    <!--
                        Top Nav

                        AVAILABLE CLASSES:
                        submenu-dark = dark sub menu
                    -->


                </div>
            </header>
            <!-- /Top Nav -->

        </div>


        
        
       
        <div class="margin-top-150">
            <div class="container">

                <div class="row">

                    <div class="col-md-6 col-md-offset-3">

                        <!-- ALERT -->
                        <div class="alert alert-mini alert-danger margin-bottom-30" id="msg">
                            <strong>Oh snap!</strong> Login Incorrect!
                        </div><!-- /ALERT -->

                        <div class="box-border-top padding-30 custgrdt" >
                            <div class="box-title margin-bottom-30">
                                <h2 class="size-20 text-white">User Credentials</h2>
                            </div>

                            <form class="nomargin" action="#" autocomplete="off">
                                <div class="clearfix">

                                    <!-- Email -->
                                    <div class="form-group">
                                        <input type="text" name="email" class="form-control" placeholder="User Name" value="pc" required="">
                                    </div>

                                    <!-- Password -->
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control" placeholder="Password" value="1234" required="">
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-md-6 col-sm-6 col-xs-6">

                                        <!-- Inform Tip -->
                                        <div class="form-tip pt-20">
                                            <a class="no-text-decoration size-13 margin-top-10 block" href="#">Forgot Password?</a>
                                        </div>

                                    </div>

                                    <div class="col-md-6 col-sm-6 col-xs-6 text-right">

                                        <input type="button" class="btn btn-primary" onclick="Login();" value="LOG IN" />

                                    </div>

                                </div>

                            </form>

                        </div>



                    </div>
                </div>

            </div>
        </div>
        



        

    </div>
    <!-- /wrapper -->
    <!-- SCROLL TO TOP -->
    <a href="#" id="toTop"></a>


    <!-- PRELOADER -->
    <div id="preloader">
        <div class="inner">
            <span class="loader"></span>
        </div>
    </div><!-- /PRELOADER -->
    <!-- JAVASCRIPT FILES -->
    <script type="text/javascript">var plugin_path = 'assets/plugins/';</script>
    <script type="text/javascript" src="/assets/plugins/jquery/jquery-2.2.3.min.js"></script>

    <script type="text/javascript" src="/assets/js/scripts.js"></script>

    <!-- STYLESWITCHER - REMOVE -->
    <script async type="text/javascript" src="/demo_files/styleswitcher/styleswitcher.js"></script>
</body>
</html>
<script type="text/javascript">

    $(document).ready(function () {
        $('#msg').css("display", "none");


    });

  

    function Login() {
        debugger;
        var Name = $('input[name=email]').val();
        var Pass = $('input[name=password]').val();
        $.ajax({
            data: {uName: Name,uPass: Pass},
            type: "POST",
            dataType: "json",
           // contentType: "application/json; charset=utf-8",
            url: "Home/LoginModel"
        }).done(function (result) {
            debugger;

            var res = result.IsLoggedIn;
         //   var aa = result["isLoggedIn"];

            if (res == 'Agency') {
                window.location.href = '@Url.Action("HomePage", "BasicOperations")';
                
            }
            else if (res == 'Admin') {
                window.location.href = '@Url.Action("AdminHome", "BasicOperations")';
            }
            else {
                $('#msg').css("display", "block");
                $('#msg').empty().append('Invalid user credentials');
            }
        }).fail(function (textStatus, errorThrown) {

            alert(textStatus);
        });
    }


</script>